package com.demo.mcp.hello;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Random;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Service;

@Service
public class HelloToolService {

    // Greets a person by name, or falls back to a friendly default when the name is missing.
    @Tool(name = "greet", description = "Say hello to someone by name. Returns a personalised greeting message.")
    public String greet(@ToolParam(description = "The name of the person to greet") String name) {
        if (name == null || name.isBlank()) {
            return "Hello, World! (no name provided)";
        }
        String trimmed = name.trim();
        return "👋 Hello, " + trimmed + "!\n"
                + "Welcome to the world of MCP (Model Context Protocol).\n"
                + "This response was generated by a Spring Boot MCP server running locally on your machine.";
    }

    // Reports the current date, time, and timezone from the machine running this server.
    @Tool(name = "get_server_time", description = "Returns the current date and time on the server. No input required.")
    public String getServerTime() {
        ZoneId zone = ZoneId.systemDefault();
        ZonedDateTime now = ZonedDateTime.now(zone);
        String date = now.format(DateTimeFormatter.ofPattern("EEEE, d MMMM uuuu", Locale.ENGLISH));
        String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        String zoneLabel = zone.getId() + " (" + now.format(DateTimeFormatter.ofPattern("z", Locale.ENGLISH)) + ")";
        return "🕐 Server Time\n"
                + "Date : " + date + "\n"
                + "Time : " + time + "\n"
                + "Zone : " + zoneLabel + "\n"
                + "\n"
                + "This time comes directly from the MCP server process running on your local machine.";
    }

    // Runs add, subtract, multiply, or divide on two numbers with safe divide-by-zero handling.
    @Tool(name = "calculate", description = "Perform basic arithmetic. Supports add, subtract, multiply and divide.")
    public String calculate(
            @ToolParam(description = "First number") double a,
            @ToolParam(description = "Operation: ADD, SUBTRACT, MULTIPLY, or DIVIDE") String operation,
            @ToolParam(description = "Second number") double b) {
        return performArithmetic(a, operation, b);
    }

    private String performArithmetic(double a, String operation, double b) {
        if (operation == null || operation.isBlank()) {
            return unknownOperationMessage(operation);
        }
        String op = operation.trim();
        String symbol;
        double result;
        String upper = op.toUpperCase(Locale.ROOT);
        if ("ADD".equals(upper) || "+".equals(op)) {
            symbol = "+";
            result = a + b;
        } else if ("SUBTRACT".equals(upper) || "-".equals(op)) {
            symbol = "-";
            result = a - b;
        } else if ("MULTIPLY".equals(upper) || "*".equals(op)) {
            symbol = "*";
            result = a * b;
        } else if ("DIVIDE".equals(upper) || "/".equals(op)) {
            if (b == 0.0d) {
                return "❌ Cannot divide by zero";
            }
            symbol = "/";
            result = a / b;
        } else {
            return unknownOperationMessage(operation);
        }
        return "🔢 Calculation Result\n"
                + formatPlain(a) + " " + symbol + " " + formatPlain(b) + " = " + formatPlain(result) + "\n"
                + "\n"
                + "Operation performed by hello-mcp-server";
    }

    // Flips a virtual coin and returns a random heads or tails message.
    @Tool(name = "flip_coin", description = "Flip a coin and get a random result. Returns HEADS or TAILS. No input required.")
    public String flipCoin() {
        boolean heads = new Random().nextBoolean();
        if (heads) {
            return "🪙 Coin Flip Result: HEADS!\n"
                    + "\n"
                    + "The coin was flipped by hello-mcp-server and landed on heads.\n"
                    + "(Each flip is completely random and independent)";
        }
        return "🪙 Coin Flip Result: TAILS!\n"
                + "\n"
                + "The coin was flipped by hello-mcp-server and landed on tails.\n"
                + "(Each flip is completely random and independent)";
    }

    private static String unknownOperationMessage(String operation) {
        String shown = operation == null ? "null" : operation;
        return "❌ Unknown operation '" + shown + "'.\n"
                + "Supported: ADD, SUBTRACT, MULTIPLY, DIVIDE";
    }

    private static String formatPlain(double value) {
        return BigDecimal.valueOf(value).setScale(4, RoundingMode.HALF_UP).stripTrailingZeros().toPlainString();
    }
}
